services:
  - type: web
    name: it-hr-asset-tracker-backend
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn backend.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
      - key: DATABASE_URL
        sync: false  # Paste your existing Render PostgreSQL connection string here
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: FRONTEND_URL
        sync: false  # Set to your Vercel URL
      - key: JWT_AUTH_SECURE
        value: "True"
      - key: CSRF_COOKIE_SECURE
        value: "True"
