# Generated by Django 5.2.13 on 2026-05-18 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='warranty_expiry',
            field=models.DateField(blank=True, null=True),
        ),
    ]
